import type { Trip, Lead, CallLog, TeamMember } from "@/types";

export const TEAM_MEMBERS: TeamMember[] = [
  { id: "tm_1", name: "Riya Kapoor", email: "riya@thenomichi.com", avatar_color: "#D55D27" },
  { id: "tm_2", name: "Arjun Mehta", email: "arjun@thenomichi.com", avatar_color: "#45471D" },
  { id: "tm_3", name: "Sana Iqbal", email: "sana@thenomichi.com", avatar_color: "#9C6B2E" },
];

export const TRIPS: Trip[] = [
  {
    id: "trip_1",
    name: "Spiti in Slow Motion",
    destination: "Spiti Valley, Himachal Pradesh",
    start_date: "2026-09-12",
    end_date: "2026-09-19",
    price_inr: 42500,
    total_seats: 12,
    seats_booked: 7,
    status: "open",
    short_description: "Cold desert villages, monasteries, and a lot of quiet.",
    description:
      "Seven days through the Spiti cold desert, moving slowly between Kaza, Langza, and Komic. No checklist of sights. Mornings are unhurried, afternoons are for walking, and evenings are spent around a stove with people you just met. Homestays throughout, small group of 12, one guide who has been doing this route for nine years.",
    cover_image: "spiti",
    created_at: "2026-05-01",
  },
  {
    id: "trip_2",
    name: "Backwaters, No Itinerary",
    destination: "Alleppey & Kumarakom, Kerala",
    start_date: "2026-08-03",
    end_date: "2026-08-07",
    price_inr: 28900,
    total_seats: 10,
    seats_booked: 4,
    status: "open",
    short_description: "A houseboat, a few villages, and nowhere to be.",
    description:
      "Five days drifting through Kerala's backwaters on a traditional houseboat, with stops in fishing villages most tourists skip. Meals are cooked on board with whatever the local market had that morning. This trip has exactly one fixed plan: there isn't one. We move when it feels right.",
    cover_image: "kerala",
    created_at: "2026-04-18",
  },
  {
    id: "trip_3",
    name: "Ladakh by Foot",
    destination: "Markha Valley, Ladakh",
    start_date: "2026-07-20",
    end_date: "2026-07-28",
    price_inr: 56000,
    total_seats: 8,
    seats_booked: 8,
    status: "closed",
    short_description: "An eight-day walk through villages, not peaks.",
    description:
      "A trekking trip built around villages rather than summits. We walk the Markha Valley at a pace that lets you actually talk to the people whose homes you're passing. Tents and homestays mixed. This batch is full — the next one opens for enquiries in October.",
    cover_image: "ladakh",
    created_at: "2026-03-02",
  },
  {
    id: "trip_4",
    name: "Konkan Coast, Off Season",
    destination: "Malvan & Tarkarli, Maharashtra",
    start_date: "2026-10-09",
    end_date: "2026-10-12",
    price_inr: 19500,
    total_seats: 14,
    seats_booked: 2,
    status: "open",
    short_description: "Quiet beaches, fish curry, and old fort towns.",
    description:
      "Four days on the Konkan coast before the crowds arrive for winter. Malvan's beaches without the noise, a boat ride to Sindhudurg fort, and meals built around whatever the fishing boats brought in. Small group, slow pace, no water sports checklist.",
    cover_image: "konkan",
    created_at: "2026-05-20",
  },
];

export const LEADS: Lead[] = [
  {
    id: "lead_1",
    name: "Ananya Roy",
    phone: "+91 98765 43210",
    email: "ananya.roy@gmail.com",
    trip_id: "trip_1",
    group_type: "friends",
    preferred_month: "September 2026",
    vibe_answer: "Honestly just want to disconnect and not plan every hour. Done one too many checklist trips.",
    status: "qualified",
    owner_id: "tm_1",
    source: "instagram",
    created_at: "2026-06-10T09:30:00Z",
    updated_at: "2026-06-14T11:00:00Z",
  },
  {
    id: "lead_2",
    name: "Karan Vohra",
    phone: "+91 99887 76655",
    email: "karan.vohra@outlook.com",
    trip_id: "trip_2",
    group_type: "couple",
    preferred_month: "August 2026",
    vibe_answer: "We want something slow and a little romantic. No big groups, no loud itineraries.",
    status: "new",
    owner_id: null,
    source: "ads",
    created_at: "2026-06-15T14:12:00Z",
    updated_at: "2026-06-15T14:12:00Z",
  },
  {
    id: "lead_3",
    name: "Priya Nair",
    phone: "+91 90123 45678",
    email: "priya.nair@yahoo.com",
    trip_id: "trip_1",
    group_type: "solo",
    preferred_month: "September 2026",
    vibe_answer: "I want to feel small next to mountains for a while. First solo trip, a little nervous.",
    status: "vibe_check_sent",
    owner_id: "tm_2",
    source: "whatsapp",
    created_at: "2026-06-08T08:00:00Z",
    updated_at: "2026-06-13T17:45:00Z",
  },
  {
    id: "lead_4",
    name: "The Malhotra Family",
    phone: "+91 98111 22334",
    email: "rajesh.malhotra@gmail.com",
    trip_id: "trip_4",
    group_type: "family",
    preferred_month: "October 2026",
    vibe_answer: "Looking for something easy with two teenagers who get bored fast. Beaches, food, not too much walking.",
    status: "contacted",
    owner_id: "tm_3",
    source: "whatsapp",
    created_at: "2026-06-12T10:20:00Z",
    updated_at: "2026-06-14T09:10:00Z",
  },
  {
    id: "lead_5",
    name: "Devika Shenoy",
    phone: "+91 97654 32109",
    email: "devika.s@gmail.com",
    trip_id: "trip_2",
    group_type: "friends",
    preferred_month: "August 2026",
    vibe_answer: "Four of us, want good food and zero rushing. Someone in the group did your Spiti trip and loved it.",
    status: "confirmed",
    owner_id: "tm_1",
    source: "instagram",
    created_at: "2026-06-01T12:00:00Z",
    updated_at: "2026-06-11T16:30:00Z",
  },
  {
    id: "lead_6",
    name: "Aditya Bhatt",
    phone: "+91 96543 21098",
    email: "aditya.bhatt@gmail.com",
    trip_id: "trip_4",
    group_type: "solo",
    preferred_month: "October 2026",
    vibe_answer: "Need a quiet weekend away from work. Not looking for parties or big groups.",
    status: "not_a_fit",
    owner_id: "tm_2",
    source: "ads",
    created_at: "2026-06-05T19:00:00Z",
    updated_at: "2026-06-09T10:00:00Z",
  },
  {
    id: "lead_7",
    name: "Meera Pillai",
    phone: "+91 95432 10987",
    email: "meera.pillai@gmail.com",
    trip_id: "trip_1",
    group_type: "couple",
    preferred_month: "September 2026",
    vibe_answer: "We loved the idea of homestays and slow mornings. Hoping to actually rest, not sightsee non-stop.",
    status: "new",
    owner_id: null,
    source: "website",
    created_at: "2026-06-16T08:45:00Z",
    updated_at: "2026-06-16T08:45:00Z",
  },
];

export const CALL_LOGS: CallLog[] = [
  {
    id: "log_1",
    lead_id: "lead_1",
    author_id: "tm_1",
    discussed: "Called to confirm trip dates work with her group. All four friends are free in September.",
    next_action: "Send vibe check questions, follow up in 2 days.",
    created_at: "2026-06-12T10:00:00Z",
  },
  {
    id: "log_2",
    lead_id: "lead_1",
    author_id: "tm_1",
    discussed: "Discussed homestay setup and what 'no itinerary' actually means day to day. She was relieved it wasn't a trekking trip.",
    next_action: "Mark as qualified, prepare vibe check message.",
    created_at: "2026-06-14T11:00:00Z",
  },
  {
    id: "log_3",
    lead_id: "lead_3",
    author_id: "tm_2",
    discussed: "First solo traveller, asked a lot about safety and group dynamics. Walked her through who else is usually on these trips.",
    next_action: "Send vibe check, mention the women-only homestay room option.",
    created_at: "2026-06-13T17:45:00Z",
  },
  {
    id: "log_4",
    lead_id: "lead_4",
    author_id: "tm_3",
    discussed: "Spoke to Rajesh. Teenagers are 14 and 16, want some activity but not full days of walking.",
    next_action: "Check if Konkan itinerary can flex for a half-day at leisure, then call back.",
    created_at: "2026-06-14T09:10:00Z",
  },
];
